default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: solaria
  password: solaria123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: solaria_development
  username: solaria
  password: solaria123

test:
  <<: *default
  database: solaria_test

production:
  <<: *default
  database: solaria_production
  username: solaria
  password: <%= ENV["SOLARIA_DATABASE_PASSWORD"] %>
